# Example Terragrunt configuration for the save-netpol-to-s3 module.
#
# Copy this directory to your Terragrunt live configuration tree and adjust
# the inputs below. The module source path assumes this example sits inside
# the module repository; update the `source` if your layout differs.

terraform {
  source = "${get_parent_terragrunt_dir()}/..//."
}

# Include the root Terragrunt config (remote state, provider defaults, etc.)
# Uncomment and adjust the path to match your project layout:
#
# include "root" {
#   path = find_in_parent_folders("root.hcl")
# }

inputs = {
  # (a) S3 bucket name where backups are saved
  s3_bucket_name = "my-network-backup-bucket"

  # (b) List of regions to back up SGs and NACLs from
  regions = ["us-east-2", "eu-central-1"]

  # (c) Schedule — defaults to daily. Override with any EventBridge expression.
  #     Examples:
  #       rate(1 day)        — every 24 hours
  #       rate(6 hours)      — every 6 hours
  #       cron(0 2 * * ? *)  — daily at 02:00 UTC
  schedule_expression = "rate(1 day)"

  # S3 path structure (auto-generated by the Lambda):
  #   s3://{bucket}/{region}/netpol/{timestamp}/security-groups.json
  #   s3://{bucket}/{region}/netpol/{timestamp}/network-acls.json
  #
  # All regions share the same timestamp so they are grouped under one backup run.
  # The timestamp is in ISO 8601 format, e.g. 2026-08-16THHMMSS (UTC).

  # Optional overrides:
  # lambda_function_name = "save-netpol-to-s3"
  # lambda_timeout       = 120
  # lambda_memory_size   = 256

  tags = {
    Environment = "prod"
  }
}
